### ISSUE TITLE
Is it compatible with Mill 0.12.x ?

### ISSUE THREAD

**Issue by zhutmost** [scala-steward-org/mill-plugin#64]
Hi, thanks for the developers' great jobs first.

Same as the title. Does Scala-Steward support the latest mill version?

I met some errors when using your GitHub action with mill. 

```log
Run scala-steward-org/scala-steward-action@v2
  with:
    author-name: GitHub Action
    author-email: action@github.com
    ....
    repo-config: ./.scala-steward.conf
    repos-file: repos.md
    ....
    github-api-url: https://api.github.com
    github-repository: zhutmost/scala-steward
    github-token: ***
    ignore-opts-files: true
    sign-commits: false
    timeout: 20min
  
✓ Default Scala Steward configuration set to: ./.scala-steward.conf
✓ Using multiple repos file: repos.md
✓ GitHub App information retrieved from GitHub
✓ Scala Steward workspace created
Trying to restore workspace contents from cache...
Launching scala-steward
  Received 11703 of 11703 (100.0%), 0.0 MBs/sec
  Error: SLF4J(I): Connected with provider of type [ch.qos.logback.classic.spi.LogbackServiceProvider]
  2024-12-29 0[5](https://github.com/zhutmost/scala-steward/actions/runs/12532660099/job/34951609826#step:4:5):04:32,259 INFO   
    ____            _         ____  _                             _
   / ___|  ___ __ _| | __ _  / ___|| |_ _____      ____ _ _ __ __| |
   \___ \ / __/ _` | |/ _` | \___ \| __/ _ \ \ /\ / / _` | '__/ _` |
    ___) | (_| (_| | | (_| |  ___) | ||  __/\ V  V / (_| | | | (_| |
   |____/ \___\__,_|_|\__,_| |____/ \__\___| \_/\_/ \__,_|_|  \__,_|
   v0.32.0
   
  2024-12-29 05:04:35,339 INFO  Loaded 295 artifact migration(s)
  2024-12-29 05:04:35,571 INFO  Loaded 3[6](https://github.com/zhutmost/scala-steward/actions/runs/12532660099/job/34951609826#step:4:6) Scalafix migration(s)
  2024-12-29 05:04:35,[7](https://github.com/zhutmost/scala-steward/actions/runs/12532660099/job/34951609826#step:4:7)27 INFO  Loaded 2 repo config(s)
  2024-12-29 05:04:35,900 INFO  Run self checks
  2024-12-29 05:04:36,251 INFO  Using git version 2.47.1
  2024-12-29 05:04:37,020 INFO  Using scalafix 0.13.0
  2024-12-29 05:04:37,[8](https://github.com/zhutmost/scala-steward/actions/runs/12532660099/job/34951609826#step:4:8)10 INFO  Using scalafmt 3.8.3
  2024-12-2[9](https://github.com/zhutmost/scala-steward/actions/runs/12532660099/job/34951609826#step:4:9) 05:04:38,625 INFO  Removing any run-specific files
  2024-12-29 05:04:38,645 INFO  ──────────── Steward zhutmost/chipmunk ────────────
  2024-[12](https://github.com/zhutmost/scala-steward/actions/runs/12532660099/job/34951609826#step:4:12)-29 05:04:38,648 INFO  Check cache of zhutmost/chipmunk
  2024-12-29 05:04:39,238 INFO  Clone zhutmost/chipmunk
  2024-12-29 05:04:39,471 INFO  Refresh cache of zhutmost/chipmunk
  2024-12-29 05:04:39,624 INFO  Get dependencies in . from Mill
  2024-12-29 05:05:07,371 ERROR Steward zhutmost/chipmunk failed
  org.scalasteward.core.buildtool.mill.parser$CirceParseError: Failed to decode Modules
  	at org.scalasteward.core.buildtool.mill.parser$.$anonfun$parseModules$1(parser.scala:43)
  	at cats.syntax.EitherOps$.leftMap$extension(either.scala:[19](https://github.com/zhutmost/scala-steward/actions/runs/12532660099/job/34951609826#step:4:19)3)
  	at org.scalasteward.core.buildtool.mill.parser$.parseModules(parser.scala:43)
  	at org.scalasteward.core.buildtool.mill.MillAlg.$anonfun$getProjectDependencies$1(MillAlg.scala:85)
  	at map @ org.scalasteward.core.buildtool.mill.MillAlg.$anonfun$getProjectDependencies$1(MillAlg.scala:84)
  	at map @ org.scalasteward.core.buildtool.mill.MillAlg.$anonfun$getProjectDependencies$1(MillAlg.scala:84)
  	at main$ @ org.scalasteward.core.Main$.main(Main.scala:23)
  	at timeoutAndForget @ org.scalasteward.core.io.process$.$anonfun$slurp$3(process.scala:85)
  	at adaptErr$extension @ org.scalasteward.core.update.artifact.ArtifactMigrationsLoader.decodeMigrations(ArtifactMigrationsLoader.scala:50)
  	at delay @ org.scalasteward.core.io.process$.$anonfun$slurp$1(process.scala:63)
  Caused by: io.circe.ParsingFailure: expected whitespace or eof got '..' (line 121, column 1)
  [20](https://github.com/zhutmost/scala-steward/actions/runs/12532660099/job/34951609826#step:4:20)24-12-29 05:05:07,374 INFO  ──────────── Total time: Steward zhutmost/chipmunk: 28s 728ms ────────────
  2024-12-29 05:05:07,384 INFO  ──────────── Total time: run: 31s 485ms ────────────
Saving workspace to cache...
Error:  ✕ Launching scala-steward failed
```

where `chipmunk` is open-sourced scala project with mill 0.12. (So the build.sc is renamed to build.mill.scala, I don't know whether this is the real reason.)

**Comment by lefou** [comment]
This plugin should work with Mill 0.12, but I too noticed, that Scala Steward isn't running properly with Mill 0.12 projects. I couldn't find the cause yet.

**Comment by fthomas** [comment]
I tried your repo in my local dev environment which has the Mill script 0.12.4 installed. It also fails, but with a slightly different error:
```
2024-12-30 09:30:06,524 ERROR Steward zhutmost/chipmunk failed
org.scalasteward.core.buildtool.mill.parser$CirceParseError: Failed to decode Modules
	at org.scalasteward.core.buildtool.mill.parser$.$anonfun$parseModules$1(parser.scala:44)
	at cats.syntax.EitherOps$.leftMap$extension(either.scala:193)
	at org.scalasteward.core.buildtool.mill.parser$.parseModules(parser.scala:44)
	at org.scalasteward.core.buildtool.mill.MillAlg.$anonfun$getProjectDependencies$1(MillAlg.scala:85)
	at map @ org.scalasteward.core.buildtool.mill.MillAlg.$anonfun$getProjectDependencies$1(MillAlg.scala:84)
	at map @ org.scalasteward.core.buildtool.mill.MillAlg.$anonfun$getProjectDependencies$1(MillAlg.scala:84)
	at main$ @ org.scalasteward.core.Main$.main(Main.scala:23)
	at timeoutAndForget @ org.scalasteward.core.io.process$.$anonfun$slurp$3(process.scala:85)
	at adaptErr$extension @ org.scalasteward.core.update.artifact.ArtifactMigrationsLoader.decodeMigrations(ArtifactMigrationsLoader.scala:50)
	at delay @ org.scalasteward.core.io.process$.$anonfun$slurp$1(process.scala:63)
Caused by: io.circe.ParsingFailure: expected whitespace or eof got 'ine 121, column 1)
```
I then `println`ed this [`input`](https://github.com/scala-steward-org/scala-steward/blob/3522159f31010f0724b895819884b1daf6a8c0cc/modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/parser.scala#L37) which gave me:
```
{
  "modules": [
    {
      "name": "mylib",
      "repositories": [
        {
          "url": "https://repo1.maven.org/maven2",
          "type": "maven",
          "auth": null,
          "headers": null
        }
      ],
      "dependencies": [
        {
          "groupId": "org.chipsalliance",
          "artifactId": {
            "name": "chisel",
            "maybeCrossName": "chisel_2.13"
          },
          "version": "6.6.0"
        },
        {
          "groupId": "org.scala-lang",
          "artifactId": {
            "name": "scala-library",
            "maybeCrossName": null
          },
          "version": "2.13.15"
        }
      ]
    },
    {
      "name": "mylib.test",
      "repositories": [
        {
          "url": "https://repo1.maven.org/maven2",
          "type": "maven",
          "auth": null,
          "headers": null
        }
      ],
      "dependencies": [
        {
          "groupId": "org.scalatest",
          "artifactId": {
            "name": "scalatest",
            "maybeCrossName": "scalatest_2.13"
          },
          "version": "3.2.19"
        },
        {
          "groupId": "org.scala-lang",
          "artifactId": {
            "name": "scala-library",
            "maybeCrossName": null
          },
          "version": "2.13.15"
        }
      ]
    },
    {
      "name": "chipmunk",
      "repositories": [
        {
          "url": "https://repo1.maven.org/maven2",
          "type": "maven",
          "auth": null,
          "headers": null
        }
      ],
      "dependencies": [
        {
          "groupId": "org.chipsalliance",
          "artifactId": {
            "name": "chisel",
            "maybeCrossName": "chisel_2.13"
          },
          "version": "6.6.0"
        },
        {
          "groupId": "org.scala-lang",
          "artifactId": {
            "name": "scala-library",
            "maybeCrossName": null
          },
          "version": "2.13.15"
        }
      ]
    },
    {
      "name": "chipmunk.test",
      "repositories": [
        {
          "url": "https://repo1.maven.org/maven2",
          "type": "maven",
          "auth": null,
          "headers": null
        }
      ],
      "dependencies": [
        {
          "groupId": "org.scalatest",
          "artifactId": {
            "name": "scalatest",
            "maybeCrossName": "scalatest_2.13"
          },
          "version": "3.2.19"
        },
        {
          "groupId": "org.scala-lang",
          "artifactId": {
            "name": "scala-library",
            "maybeCrossName": null
          },
          "version": "2.13.15"
        }
      ]
    }
  ]

[31/31] =============== show org.scalasteward.mill....StewardPlugin/extractDeps =============== 9s
```
That is not valid JSON, it is truncated and contains this timing info `[31/31] ===`.

**Comment by fthomas** [comment]
It seems to work if I add `--ticker=false` [here](https://github.com/scala-steward-org/scala-steward/blob/3522159f31010f0724b895819884b1daf6a8c0cc/modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala#L50).

**Comment by lefou** [comment]
Nice observation! Since the used mill commnad is `show`, which should output the result to STDOUT and everything else to STDERR, the `--ticker=false` "should" not be necessary. So, we either capture too much (STDERR) or there is a issue in Mill 0.12.

**Comment by lefou** [comment]
disabling the ticker is probably a good idea in any case, since we're processing the Mill output programmatically. @fthomas Can you open a PR? This might unblock many projects.

**Comment by fthomas** [comment]
PR is here: https://github.com/scala-steward-org/scala-steward/pull/3511

**Comment by fthomas** [comment]
Even if Mill uses stderr and stdout, Scala Steward merges both: https://github.com/scala-steward-org/scala-steward/blob/3522159f31010f0724b895819884b1daf6a8c0cc/modules/core/src/main/scala/org/scalasteward/core/io/process.scala#L99

**Comment by lefou** [comment]
Thank you @fthomas !
